apiVersion: v1
kind: ServiceAccount
metadata:
  name: remediator
  namespace: demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: remediator-trivy-reader
  namespace: demo
rules:
  - apiGroups: ["aquasecurity.github.io"]
    resources: ["vulnerabilityreports"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: remediator-trivy-reader
  namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: remediator-trivy-reader
subjects:
  - kind: ServiceAccount
    name: remediator
    namespace: demo
